PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX aiiso: <http://purl.org/vocab/aiiso/schema#>
PREFIX owl: <http://w3.org/2002/07/owl#>
PREFIX sch: <http://schema.org/>

PREFIX stats: <http://stats.org/vocab#>
PREFIX ac: <http://academie.fr/vocab#>

CONSTRUCT {
	?URI a owl:Statistic;
		owl:year ?annee;
		dbo:diploma ?diplome;
		owl:location ?etablissement;
		ac:codeAcademie ?code_de_l_academie;		# aiiso:code?
		ac:academie ?academie;						# aiiso:organization?
		ac:codeDomaine ?code_du_domaine;
		ac:domaine ?domaine;						# aiiso:department?
		ac:codeDiscipline
		ac:discipline ?discipline;					# aiiso:subject?
		stats:period ?situation;						# owl:period?
		stats:answerCount ?nombre_de_reponses;		# sch:answerCount?
		stats:answerRatio ?taux_de_reponses;
		ac:subjectWeight ?poids_de_la_discipline;
		stats:employmentRate ?taux_dinsertion;
		stats:?? ?emplois_cadre_ou_professions_intermediaires;
		stats:numberOfStableJobs ?emplois_stables;
		stats:numberOfFullTimeJobs ?emplois_a_temps_plein;
		
		
		dbo:salary ?salaire_brut_annuel_estime;
		stats:
		

}
FROM <file:fr-esr-insertion_professionnelle-lp.csv>
WHERE {
	BIND(URI(CONCAT('http://ex.org/Project/', ?annee))AS ?URI)
	BIND (xsd:integer(?no) AS ?annee)
}
