PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX aiiso: <http//purl.org/vocab/aiiso/schema#>
PREFIX owl: <http://w3.org/2002/07/owl#>
PREFIX ex: <http://example.org/project>
PREFIX ac: <http://academie.fr/vocab#>
PREFIX stats: <http://stats.org/vocab#>


### Nombre de femmes par domaine, academie et discipline

SELECT  ?domaine ?discipline ?academie ?femmes
WHERE {
	?p 	ac:domaine ?domaine;
     	ac:discipline ?discipline;
      	ac:academie ?academie;
		ex:femmes ?femmes.
}
ORDER BY DESC (?femmes)

##Donne le pourcentage de personne ayant trouvé un emploi à plein temps par discipline et académie
SELECT ?discipline ?academie ?nbFullTimeJob
WHERE{
	?p ac:academie ?academie;
	   ac:discipline ?discipline;
	   stats:numberOfFullTimeJobs  ?nbFullTimeJob
	
}
ORDER BY DESC (?academie)
