PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbo: <http://dbpedia.org/ontology/>
#PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX aiiso: <http://purl.org/vocab/aiiso/schema#>
PREFIX owl: <http://w3.org/2002/07/owl#>
#PREFIX sch: <http://schema.org/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX stats: <http://stats.org/vocab#>
PREFIX ac: <http://academie.fr/vocab#>
PREFIX ex:<http://example.org/project>

CONSTRUCT {

	

	?URI a owl:Statistic;
		owl:year ?annee;
		dbo:diploma ?diplome;
		ex:num_etabli ?num_de_l_etablissement;
		owl:location ?etablissement;
		ac:academie ?academie;						# aiiso:organization?
		aiiso:code ?URI_id_academie;
		ac:codeDomaine ?code_du_domaine;
		ac:domaine ?domaine;						# aiiso:department?
		ac:codeDiscipline ?code_de_la_discipline;
		ac:discipline ?discipline;					# aiiso:subject?
		owl:period ?situation;					
		stats:answerCount ?nombre_de_reponses;		# sch:answerCount?
		stats:answerRatio ?taux_de_reponse;
		ac:subjectWeight ?poids_de_la_discipline;
		stats:employmentRate ?taux_d_insertion;

		ex:emplois ?emplois_cadre_ou_professions_intermediaires;

		stats:numberOfStableJobs ?emplois_stables;
		stats:numberOfFullTimeJobs ?emplois_a_temps_plein;
		
		ex:salaireMedian ?salaire_net_median_des_emplois_a_temps_plein;
		ex:salaireBrutAnnuel ?salaire_brut_annuel_estime;
		ex:pourcentageDiplomesBoursiers ?de_diplomes_boursiers;
		ex:chomageregional ?taux_de_chomage_regional;
		ex:salaireMensuelRegional ?salaire_net_mensuel_median_regional;
		ex:pourcentageEmploisCadre ?emplois_cadre;
		ex:pourcentageEmploisExterieurs ?emplois_exterieurs_a_la_region_de_l_universite;
		ex:pourcentageFemmes ?femmes;
		ex:salaireNetMensuel_first_quartile ?salaire_net_mensuel_regional_1er_quartile;
		ex:salaireNetMensuel_third_quartile ?salaire_net_mensuel_regional_3eme_quartile;
		ex:cleETAB ?cle_ETAB.
		
		#Données à lier.
		?URI_id_academie rdf:type aiiso:code;
				owl:sameAs ?URI_id_academie_EES.
}
FROM <file:fr-esr-insertion_professionnelle-lp.csv>

WHERE {

	BIND(URI(CONCAT("http://ex.org/projet/", ?academie, ?discipline, ?domaine))AS ?URI)

	BIND(URI(CONCAT("http://ex.org/projet/id_aca/", ?code_de_l_academie))AS ?URI_id_academie)
	BIND(URI(CONCAT("http://ex.org/projet/id_aca/", ?code_de_l_academie))AS ?URI_id_academie_EES)
}

